# Generated by Django 4.2.1 on 2023-07-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='itemsimg',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
